services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tixmaster
      POSTGRES_PASSWORD: passw0rd
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
# volumes:
# db_data:
