services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tixmaster
      POSTGRES_PASSWORD: passw0rd
    # volumes:
    #   - db_data:/var/lib/postgresql/data
# volumes:
# db_data:
