// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: host.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const newHost = `-- name: NewHost :one
insert into host (name, avatar, bio) values ($1, $2, $3) returning host_id, name, avatar, bio
`

type NewHostParams struct {
	Name   string
	Avatar string
	Bio    string
}

type NewHostRow struct {
	HostID pgtype.UUID
	Name   string
	Avatar string
	Bio    string
}

func (q *Queries) NewHost(ctx context.Context, arg NewHostParams) (NewHostRow, error) {
	row := q.db.QueryRow(ctx, newHost, arg.Name, arg.Avatar, arg.Bio)
	var i NewHostRow
	err := row.Scan(
		&i.HostID,
		&i.Name,
		&i.Avatar,
		&i.Bio,
	)
	return i, err
}
