// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tixmaster

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    pgtype.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
