// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: venue.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const newVenue = `-- name: NewVenue :one
insert into venue (name, capacity, city, state, img)
values ($1, $2, $3, $4, $5)
returning venue_id, name, capacity, city, state, img
`

type NewVenueParams struct {
	Name     string
	Capacity int32
	City     string
	State    string
	Img      string
}

type NewVenueRow struct {
	VenueID  pgtype.UUID
	Name     string
	Capacity int32
	City     string
	State    string
	Img      string
}

func (q *Queries) NewVenue(ctx context.Context, arg NewVenueParams) (NewVenueRow, error) {
	row := q.db.QueryRow(ctx, newVenue,
		arg.Name,
		arg.Capacity,
		arg.City,
		arg.State,
		arg.Img,
	)
	var i NewVenueRow
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.Capacity,
		&i.City,
		&i.State,
		&i.Img,
	)
	return i, err
}
